# coding: utf-8

"""
    Labelling

    Generates a Base64 label  # noqa: E501

    OpenAPI spec version: v2_2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import postnl_service_shipment
from postnl_service_shipment.models.request import Request  # noqa: E501
from postnl_service_shipment.rest import ApiException


class TestRequest(unittest.TestCase):
    """Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequest(self):
        """Test Request"""
        # FIXME: construct object with mandatory attributes with example values
        # model = postnl_service_shipment.models.request.Request()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
