# coding: utf-8

"""
    Labelling

    Generates a Base64 label  # noqa: E501

    OpenAPI spec version: v2_2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import postnl_service_shipment
from postnl_service_shipment.models.request_customer_address import RequestCustomerAddress  # noqa: E501
from postnl_service_shipment.rest import ApiException


class TestRequestCustomerAddress(unittest.TestCase):
    """RequestCustomerAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestCustomerAddress(self):
        """Test RequestCustomerAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = postnl_service_shipment.models.request_customer_address.RequestCustomerAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
