# coding: utf-8

# flake8: noqa
"""
    Labelling

    Generates a Base64 label  # noqa: E501

    OpenAPI spec version: v2_2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from postnl_service_shipment.models.error import Error
from postnl_service_shipment.models.error_errors import ErrorErrors
from postnl_service_shipment.models.request import Request
from postnl_service_shipment.models.request_addresses import RequestAddresses
from postnl_service_shipment.models.request_amounts import RequestAmounts
from postnl_service_shipment.models.request_contacts import RequestContacts
from postnl_service_shipment.models.request_content import RequestContent
from postnl_service_shipment.models.request_customer import RequestCustomer
from postnl_service_shipment.models.request_customer_address import RequestCustomerAddress
from postnl_service_shipment.models.request_customs import RequestCustoms
from postnl_service_shipment.models.request_dimension import RequestDimension
from postnl_service_shipment.models.request_extra_fields import RequestExtraFields
from postnl_service_shipment.models.request_groups import RequestGroups
from postnl_service_shipment.models.request_hazardous_material import RequestHazardousMaterial
from postnl_service_shipment.models.request_message import RequestMessage
from postnl_service_shipment.models.request_product_options import RequestProductOptions
from postnl_service_shipment.models.request_shipments import RequestShipments
from postnl_service_shipment.models.response import Response
from postnl_service_shipment.models.response_labels import ResponseLabels
from postnl_service_shipment.models.response_merged_labels import ResponseMergedLabels
from postnl_service_shipment.models.response_response_shipments import ResponseResponseShipments
from postnl_service_shipment.models.response_warnings import ResponseWarnings
