# coding: utf-8

"""
    Labelling

    Generates a Base64 label  # noqa: E501

    OpenAPI spec version: v2_2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RequestDimension(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'height': 'str',
        'length': 'str',
        'volume': 'str',
        'weight': 'str',
        'width': 'str'
    }

    attribute_map = {
        'height': 'Height',
        'length': 'Length',
        'volume': 'Volume',
        'weight': 'Weight',
        'width': 'Width'
    }

    def __init__(self, height=None, length=None, volume=None, weight='2000', width=None):  # noqa: E501
        """RequestDimension - a model defined in Swagger"""  # noqa: E501
        self._height = None
        self._length = None
        self._volume = None
        self._weight = None
        self._width = None
        self.discriminator = None
        if height is not None:
            self.height = height
        if length is not None:
            self.length = length
        if volume is not None:
            self.volume = volume
        self.weight = weight
        if width is not None:
            self.width = width

    @property
    def height(self):
        """Gets the height of this RequestDimension.  # noqa: E501

        Height of the shipment in milimeters (mm).  # noqa: E501

        :return: The height of this RequestDimension.  # noqa: E501
        :rtype: str
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this RequestDimension.

        Height of the shipment in milimeters (mm).  # noqa: E501

        :param height: The height of this RequestDimension.  # noqa: E501
        :type: str
        """

        self._height = height

    @property
    def length(self):
        """Gets the length of this RequestDimension.  # noqa: E501

        Length of the shipment in milimeters (mm).   # noqa: E501

        :return: The length of this RequestDimension.  # noqa: E501
        :rtype: str
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this RequestDimension.

        Length of the shipment in milimeters (mm).   # noqa: E501

        :param length: The length of this RequestDimension.  # noqa: E501
        :type: str
        """

        self._length = length

    @property
    def volume(self):
        """Gets the volume of this RequestDimension.  # noqa: E501

        Volume of the shipment in centimeters (cm3). Mandatory for E@H-products  # noqa: E501

        :return: The volume of this RequestDimension.  # noqa: E501
        :rtype: str
        """
        return self._volume

    @volume.setter
    def volume(self, volume):
        """Sets the volume of this RequestDimension.

        Volume of the shipment in centimeters (cm3). Mandatory for E@H-products  # noqa: E501

        :param volume: The volume of this RequestDimension.  # noqa: E501
        :type: str
        """

        self._volume = volume

    @property
    def weight(self):
        """Gets the weight of this RequestDimension.  # noqa: E501

        Weight of the shipment in grams. Approximate weight suffices  # noqa: E501

        :return: The weight of this RequestDimension.  # noqa: E501
        :rtype: str
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """Sets the weight of this RequestDimension.

        Weight of the shipment in grams. Approximate weight suffices  # noqa: E501

        :param weight: The weight of this RequestDimension.  # noqa: E501
        :type: str
        """
        if weight is None:
            raise ValueError("Invalid value for `weight`, must not be `None`")  # noqa: E501

        self._weight = weight

    @property
    def width(self):
        """Gets the width of this RequestDimension.  # noqa: E501

        Width of the shipment in milimeters (mm).   # noqa: E501

        :return: The width of this RequestDimension.  # noqa: E501
        :rtype: str
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this RequestDimension.

        Width of the shipment in milimeters (mm).   # noqa: E501

        :param width: The width of this RequestDimension.  # noqa: E501
        :type: str
        """

        self._width = width

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestDimension, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestDimension):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
